apiVersion: v2
name: nfs-storageClass
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: csi-driver-nfs
    version: "4.11.0"
    repository: "https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts"