
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.secretStoreRef.grafana.name }}
  namespace: {{ .Values.secrets.secretStoreRef.grafana.namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/resource-policy: delete
spec:
  refreshInterval: {{ .Values.secrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secrets.secretManager }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secrets.secretStoreRef.grafana.targetName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        admin-user: admin
        {{ .Values.secrets.secretStoreRef.grafana.passwordKey }}: "{{`{{ .pwKey }}`}}"
  data:
    - secretKey: pwKey
      remoteRef:
        key: "{{ .Values.secrets.secretStoreRef.grafana.name }}"