apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.secretStoreRef.teamsWebhookUrl.name }}
  namespace: {{ .Values.secrets.secretStoreRef.teamsWebhookUrl.namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/resource-policy: delete
spec:
  refreshInterval: {{ .Values.secrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secrets.secretManager }}
    kind: ClusterSecretStore
  data:
    - secretKey: {{ .Values.secrets.secretStoreRef.teamsWebhookUrl.key }}
      remoteRef:
        key: "{{ .Values.secrets.secretStoreRef.teamsWebhookUrl.name }}"
